export const USER_REGIST = "USER_REGIST" //注册
export const USER_REGIST_RESULT = "USER_REGIST_RESULT" //注册结果
export const USER_UNLOAD="USER_UNLOAD" //清理数据
export const USER_LOGIN_RESULT="USER_LOGIN_RESULT" //登陆结果
export const PROFILE_GET_RESULT="PROFILE_GET_RESULT" //用户信息获取结果
export const USER_SYNC_RESULT = "USER_SYNC_RESULT" //同步用户信息
export const PROFILE_POST_RESULT = "PROFILE_POST_RESULT" // 关注
export const PROFILE_DELETE_RESULT = "PROFILE_DELETE_RESULT" // 取关
export const USER_UPDATE_RESULT = "USER_UPDATE_RESULT" // 更新个人信息
export const USER_SETTING_LOGOUT = "USER_SETTING_LOGOUT" //退出登录
export const ARTICLES_AUTHOR_RESULT = "ARTICLES_AUTHOR_RESULT " // 获取作者文章结果
export const ARTICLES_LIKE_RESULT = "ARTICLES_LIKE_RESULT " // 获取作者喜欢的文章结果
export const ARTICLE_UPDATE_FIELD = "ARTICLE_UPDATE_FIELD " // 新建文章字段同步
export const ARTILE_ADD_TAG = "ARTILE_ADD_TAG " // 新建标签
export const ARTILE_REMOVE_TAG = "ARTILE_REMOVE_TAG " // 移除标签
export const ARTICLE_CREATE_RESULT = "ARTICLE_CREATE_RESULT " // 移除标签
export const ARTICLE_UNLOAD = "ARTICLE_UNLOAD " // 移除标签
export const ARTICLE_GET_RESULT = "ARTICLE_GET_RESULT " // 获取文章结果
export const ARTICLE_UPDATE_RESULT = "ARTICLE_UPDATE_RESULT " // 获取文章结果
export const COMMENT_UPDATE_FIELD = "COMMENT_UPDATE_FIELD " // 评论字段同步
export const COMMENT_CREATE_RESULT = "COMMENT_CREATE_RESULT " // 创建评论结果
export const COMMENT_DELETE_RESULT = "COMMENT_DELETE_RESULT " // 创建评论结果
export const COMMENTS_GET_RESULT = "COMMENTS_GET_RESULT " // 创建评论结果
export const ARTICLE_DELETE_RESULT = "ARTICLE_DELETE_RESULT " // 删除文章结果
export const ARTICLE_FAVORITE_RESULT = "ARTICLE_FAVORITE_RESULT " // 喜欢文章结果


